class Effect
{
    ttl=0;
    expired = false;
    stateffects=[];
    constructor(boosts,ttl)
    {
        this.stateffects.push(...boosts);
        this.ttl=ttl;
    }
    apply(target)
    {
        this.stateffects.forEach((e)=>{
            target.stats.add(e);
        });
    }
    remove(target)
    {
        this.stateffects.forEach((e)=>{
            target.stats.remove(e);
        });
    }
    update(dT)
    {
        this.ttl-=dT;
        if(this.ttl<=0)
        {
            this.expired=true;
        }
    }
}